### PR TITLE
Created calendar year and updated tests

### PR DESCRIPTION
**Pull request by johanwesteinde**
Removed some unused variables in the tests as well (that weren't CalendarYear type).

You can ignore the "Added ..." and "Revert ..." commits cause there was a mixup in what I was supposed to be doing, so it's just the last commit that needs reviewing.

### CODE REVIEW

**Comment by TGLS** [comment]
Can you add CalendarYear to program to please?

**Comment by TGLS** [comment]
Also: CalendarYear should be associated with Course not LearningObjective

**Comment by johanwesteinde** [comment]
Comments attended to, good for another review @TGLS

**Comment by TGLS** [comment]
Can you change Program's association to Calendar Year to be Many-to-Many (Idea is that many Programs can share calendar years, and a program can have more than one calendar year as programs may remain unchanged for more than one year)

**Comment by johanwesteinde** [comment]
Comments tended to, back to you @TGLS

**Comment by LawKyle** [comment]
I just tested the merge locally, with no issues.

**Pull request merged**
